var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                    o                           ",
   "                                    o o       o    xxx                      xxx ",
   "                                              xx               xxxx    o    x   ",
   "  xxxx                             xxxxx                       x!!x   xxx   x   ",
   "  x                                        o                   x!!x  o!!x   xx  ",
   "  x                                        x!x                       o!!x    x  ",
   "  x                                        xxx                      xx!!x    x  ",
   "  x       y                    o     xxxxx                                 o x  ",
   "  x      xxx      o           xxx                                xxx         x  ",
   "  x  @   x x                  x x   o                            x x   w     x  ",
   "  xxxxxxxx xxxxxx  xxxxxxxppxxx xxxxx!!!!!!!!xxxxxxxxx!!!xxxxxxxxx xxxxxxxxxxx  ",
   "                x!!x     xppx       x!!!!!!!!x       x!!!x                      ",
   "                x!!x     xppx       xxxxxxxxxx       x!!!x                      ",
   "                xxxx     xxxx                        xxxxx                      ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                   !!!                                                                            ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                           w                      ",
   "                                                                                          xxxx                    ",
   "                          o                                                                                       ",
   "                        xxxxx            o  o                                                                     ",
   "x                                      xxxxxxxxx                         o                                        ",
   "x                                                                  o    xxxxxxxxx                                 ",
   "x                               o                                xxxx       x                                     ",
   "x                  o         xxxxxxx                   o                    x    xxxx                             ",
   "x                xxxxx                               xxxxxx                 x         o                           ",
   "x       y                                                                   x        xxxx    o                    ",
   "x      xxxx                               !xxxx                             x               xxxx            o  o  ",
   "x     !x  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx  xpppppppppppppppppppppppppppppx!!!!!!!!!!!!!!!!!xxxxxxx   xxxxxxxxxx",
   "x  @  !x  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     xpppppppppppppppppppppppppppppx!!!!!!!!!!!!!!!!!      x!!!!x        ",
   "xxxxxxxx  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     xpppppppppppppppppppppppppppppx!!!!!!!!!!!!!!!!!      xxxxxx        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                               xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!",
   "                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                  x                                       pppp",
   "                                                                  x                                           ",
   "                                                                  x                                           ",
   "                                                                  x                oxxxxxxxxxxxxxxx           ",
   "                                                                  x               xxx             x           ",
   "                                                o                 x             xxx               x           ",
   "                                                                  x           xxx                 x        !p!",
   "                                            o xppx o                      ooxxx                   xo          ",
   "                                           xxxxppxxxx o              oo xxxx                      xxxx        ",
   "   o                                   oxxxx!!!!!!!!!xxxx o         xxxxx                         x!p!        ",
   "xxxxxx        o                     oxxxx!!!!!!!!!!!!!!!xxxx o     xx                             x         o ",
   "     x                             xxxx!!!!!!!!!!!!!!!!!!!!xxxxoo  xx                             x        xxx",
   "     x                           xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx                             x        !!!",
   "     x  @              y         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                             xo          ",
   "xxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                             xxxx        ",
   "           x!!!!!!x               !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                             x      w o  ",
   "           xxxxxxxx               !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                             xpppppxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                      x   x  x  x  x x xx   x x                                               ",
   "                                      x   x  x  x  x x x x  x x                                               ",
   "                                      x @ x  x  x  x x x  x x x                                               ",
   "                                      xxxxx  xxxxxxx x x   xx                                                 ",
   "                                                              x                                               "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
